
name: ci-tests
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    environment:
      name: test
    steps:
      - uses: actions/checkout@v3
      - name: Get Go Version
        run: |
          #!/bin/bash
          GOVERSION=$({ [ -f .go-version ] && cat .go-version; })
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'
      - name: Clean Up Environment
        run: |
          #!/bin/bash
          # clean cache
          go clean -testcache
      - name: Run Unit Tests
        run: |
          #!/bin/bash
          go test -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: github.com/jairad26/slug_generator
          threshold: 80
          threshold-package: 80
          threshold-total: 95

          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges
